### ISSUE TITLE
Invalid mention

### ISSUE THREAD

**Issue by hassan** [Heath123/CredentialReminderBot#3]
The bot response [here](https://github.com/HassanCorrigan/watchlisted/commit/37918adc13c37d0b2d381b16a824f20b62347ece#commitcomment-47093713) starts out with:

`"Hello @hassan Corrigan," `

rather than (presumably) @HassanCorrigan. Or whoever, but assuredly not me (@hassan) 😀

**Comment by Heath123** [comment]
I noticed this in some other places too... I must be using the real name, not the username. Thanks for the bug report

**Comment by Heath123** [comment]
Should be fixed by https://github.com/Heath123/CredentialReminderBot/commit/2b4a50d87c9b7eb6121e876d08ed56a80fc3a087
Now it will try to use your GitHub username, or if the author doesn't have an account, it will still fall back to the real name, but this time it's won't try to ping them.
