### ISSUE TITLE
typo / mistaken sentence?

### ISSUE THREAD

**Issue by itamarcu** [Heath123/CredentialReminderBot#4]
In a message that the bot [gave me](https://github.com/itamarcu/FoundryVTT-KryxRPG/commit/4bf079b9d3ffb6df6c07c72817c3ccc70c6da695), it said:

> The right thing to do is to change your password or invalidate your token _now_. If this is not possible, see [here](https://stackoverflow.com/questions/872565/remove-sensitive-files-and-their-commits-from-git-history) for info about removing this file from Git history and hope that other bots or people saw it. 

I think this is a mistake - it should be saying ..."people **didn't see** it".

**Comment by Heath123** [comment]
Good point :)

**Comment by Heath123** [comment]
I missed the word "no"

**Comment by Heath123** [comment]
Fixed in https://github.com/Heath123/CredentialReminderBot/commit/f729abb197a24afe9df0bb52a5ac4d964c9824ae
